### ISSUE TITLE
How do you edit an entry?

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/dataportals.org#47]
Brisbane City Council in Australia has updated its open data portal to https://www.data.brisbane.qld.gov.au. How do you edit an existing entry?

**Comment by mattfullerton** [comment]
Well... this is one way. I've updated it :smile:

**Comment by Stephen-Gates** [comment]
Thanks @mattfullerton
are there plans to improve data portal.org? It seems a little quiet.

**Comment by rgrp** [comment]
@Stephen-Gates it is quite easy to update - there is a google spreadsheet which editors manage. We are on the look out for new editors so if you are interested please say :-)

**Comment by mattfullerton** [comment]
There are no fixed plans. Do you think its a valuable service?

**Comment by rgrp** [comment]
@Stephen-Gates current managing editors are http://okfnlabs.org/members/schlos/ and http://okfnlabs.org/members/mattfullerton/ - project page is http://okfnlabs.org/projects/dataportals/

**Comment by rgrp** [comment]
@Stephen-Gates and @mattfullerton - we also do have *plans* for various improvements - see the issue tracker. The issue is simply someone to volunteer to do or sponsor that work ;-) (I note @mattfullerton did absolutely stirling work last year making some major improvements and that @schlos has been doing a great job managing new submissions).

**Comment by mattfullerton** [comment]
Sorry, you're right, there are of course plans. Rather there are no fixed plans/resources for implementation :smile: 

@Stephen-Gates @rgrp What I would really love to see is more collection of the metadata endpoints of catalogs so that if someone wants to say, collect an index of all open data within a geographic region, they can do that quickly and easily using the site as an API.

**Comment by Stephen-Gates** [comment]
@mattfullerton I do find it useful but also find it difficult to contribute new portals due to the level of detail required. Some things only the portal owner would know or they're hard to find out. Thanks for you efforts to date.

@rgrp would adding a [discussion forum](https://discuss.okfn.org) category or topic under [open government data](https://discuss.okfn.org/c/working-groups/open-gov-data) help raise the profile and broaden the audience? Happy to do that.

**Comment by rgrp** [comment]
@Stephen-Gates +1 on the discussion forum. Also we could make it lighter weight to get info in - you don't need all the data to get the portal up there - more data can be added later.

**Comment by Stephen-Gates** [comment]
@rgrp happy to be an editor for Australia.

**Comment by Stephen-Gates** [comment]
@mattfullerton do you mean collecting e.g a CKAN endpoint like this https://data.qld.gov.au/api/3/action/package_list to list all datasets in a portal?

@rgrp can't seem to add sub-category in the forum - see https://discuss.okfn.org/t/new-category-ideas/56/20

**Comment by mattfullerton** [comment]
@Stephen-Gates Yes - here is an example:
http://dataportals.org/catalog/rheinland-pfalz

Its not the best example because the complete metadata is coming from a third party site. For your particular example the two fields would be
https://data.qld.gov.au/api and
https://data.qld.gov.au/api/3/action/current_package_list_with_resources

Which all begs the question whether we shouldn't just have a simple URL submit option and let the editor do the hard work :wink: 

I've added the fields concerning the API.

**Comment by Stephen-Gates** [comment]
@mattfullerton @rgrp [DataPortals.org category](https://discuss.okfn.org/c/open-knowledge-labs/dataportals) added to Open Knowledge discussion forum.

Let me know what I need to do to take on the editor role.

**Comment by mattfullerton** [comment]
Just send me your (preferably Google) email address - matt dot fullerton AT gmail.com
