### ISSUE TITLE
Use of Inactive Tag?

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/dataportals.org#52]
A portal was [reported](https://discuss.okfn.org/t/help-make-the-most-comprehensive-list-of-open-data-portals-around-the-world/925/6?u=stephen) as no longer being available. I changed the value in the Google sheet from `active` to `inactive` thinking this would hide [the portal on DataPortals.org](http://dataportals.org/catalog/korea-datahub). This only changed the Status and the portal still appears in the website.

How should a portal be removed/hidden?
- delete the row in the Google sheet
- change the query to not select `inactive` sites
- some other trick?

<img width="666" alt="screenshot 2015-08-17 19 59 04" src="https://cloud.githubusercontent.com/assets/9379524/9302523/89fbbb64-451a-11e5-847a-a8c6825ac296.png">

**Comment by rgrp** [comment]
I think inactive is better and then we should hide (at least from search and map) and prominently mark as inactive on the individual page.

**Comment by mattfullerton** [comment]
If we hide it from search and map, no one will ever find it (my guess), so I don't see much point in keeping the individual page. I don't want to make things more complicated, but active/inactive probably refers to whether something is actively maintained - it should still be there and perhaps has interesting data available. If a site is completely gone, I would say it should be archived but completely removed from the site. The quickest solution is to create a duplicate (same headers, no data) sheet in GDocs, and copy over defunct rows.

I still agree with making the inactive label more prominent, but like I say, for inactive rather than disappeared sites.

**Comment by rgrp** [comment]
@mattfullerton keeping the individual page is because people may have already been linking to it. I thought "inactive" meant gone (evaluating activity otherwise is a subtle exercise). Very happy to have you and @Stephen-Gates decide on this one and implement :-)

**Comment by Stephen-Gates** [comment]
Whatever we decide, let's drop a comment in the Google sheet column so others will know the definition. Personally I like @rgrp's suggestion for the reasons given and as a newbie that's how I expected it to work.

**Comment by jgkim** [comment]
+1 for @rgrp's suggestion. If it's hidden from search and map, we still can see it on the list.

**Comment by augusto-herrmann** [comment]
The [description of the field](https://github.com/okfn/dataportals.org/blob/a578997ee44580bdb9eb007e2511370cfc0fefd7/data/datapackage.json#L119) is clear that an inactive portal means it is currently unavailable. So I guess this discussion is settled and we can move on to implementation – I've opened issue #256 for that.
